# -*- coding: utf-8 -*-
"""analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ackqceelv1Qqfaw1trnRB5SIqY5t-vem
"""

from scipy.stats import pearsonr
import statsmodels.api as sm


def pearson_correlation(df, variable_x, variable_y):
    """Calculate Pearson correlation and p-value."""
    analysis_df = df[[variable_x, variable_y]].dropna()

    correlation, p_value = pearsonr(
        analysis_df[variable_x],
        analysis_df[variable_y]
    )

    return correlation, p_value, len(analysis_df)


def simple_ols(df, predictor, target):
    """Fit a simple ordinary least squares regression."""
    analysis_df = df[[predictor, target]].dropna()

    X = analysis_df[[predictor]]
    y = analysis_df[target]

    X = sm.add_constant(X)

    model = sm.OLS(y, X).fit()

    return model


def multiple_ols(df, predictors, target):
    """Fit a multiple ordinary least squares regression."""
    columns = [target] + predictors
    analysis_df = df[columns].dropna()

    X = analysis_df[predictors]
    y = analysis_df[target]

    X = sm.add_constant(X)

    model = sm.OLS(y, X).fit()

    return model