# -*- coding: utf-8 -*-
"""data_cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UavRwYPgCyoiCjd8tgRyKvx24T0pT6Y3
"""

import pandas as pd


def load_data(file_path):
    """Load a CSV dataset."""
    df = pd.read_csv(file_path)
    return df


def check_missing_values(df):
    """Return missing-value counts and percentages."""
    missing_count = df.isna().sum()
    missing_percentage = (df.isna().mean() * 100).sort_values(ascending=False)

    return missing_count, missing_percentage


def check_duplicates(df):
    """Return the number of duplicate rows."""
    return df.duplicated().sum()


def prepare_year_column(df):
    """Convert Year to numeric and sort the dataset chronologically."""
    df = df.copy()
    df["Year"] = pd.to_numeric(df["Year"], errors="coerce")
    df = df.sort_values("Year").reset_index(drop=True)

    return df