# -*- coding: utf-8 -*-
"""visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MORmLykbeESvk3v6vKQn75WViERUk1ij
"""

import matplotlib.pyplot as plt
import seaborn as sns


def plot_time_series(df, variable, title, y_label):
    """Plot an indicator over time."""
    plt.figure(figsize=(12, 6))

    plt.plot(
        df["Year"],
        df[variable],
        linewidth=2
    )

    plt.title(title)
    plt.xlabel("Year")
    plt.ylabel(y_label)

    plt.tight_layout()
    plt.show()


def plot_correlation_heatmap(df, title="Correlation Between Development Indicators"):
    """Create a correlation heatmap for numeric variables."""
    numeric_df = df.select_dtypes(include="number")
    correlation = numeric_df.corr()

    plt.figure(figsize=(14, 10))

    sns.heatmap(
        correlation,
        annot=True,
        fmt=".2f",
        linewidths=0.5
    )

    plt.title(title)
    plt.tight_layout()
    plt.show()


def plot_relationship(df, x, y, title):
    """Create a scatter plot with a regression line."""
    analysis_df = df[[x, y]].dropna()

    plt.figure(figsize=(10, 6))

    sns.regplot(
        data=analysis_df,
        x=x,
        y=y
    )

    plt.title(title)
    plt.tight_layout()
    plt.show()